/**
 * Rutas registradas en el SPA admin (React Router).
 * Mantener alineado con src/app/routes.jsx y materialRoutes / sessionRoutes.
 */
export const ADMIN_SPA_ROUTES = [
  { path: "/", label: "Redirección inicio", grupo: "admin" },
  { path: "/dashboard/default", label: "Dashboard", grupo: "admin" },
  { path: "/charts/echarts", label: "Gráficos ECharts", grupo: "admin" },
  { path: "/clientes-ventas/index", label: "Clientes ventas", grupo: "admin" },
  { path: "/empleados/index", label: "Empleados", grupo: "admin" },
  { path: "/vendedor/index", label: "Vendedor", grupo: "admin" },
  { path: "/backup/index", label: "Backup", grupo: "admin" },
  { path: "/beneficio/index", label: "Beneficio", grupo: "admin" },
  { path: "/usuarios/index", label: "Usuarios", grupo: "admin" },
  { path: "/perfiles/index", label: "Perfiles", grupo: "admin" },
  { path: "/roles/index", label: "Roles", grupo: "admin" },
  { path: "/menu/index", label: "Menú", grupo: "admin" },
  { path: "/menu/orden", label: "Orden de mi menú", grupo: "admin" },
  { path: "/objetos/index", label: "Objetos", grupo: "admin" },
  { path: "/profile/index", label: "Mi perfil", grupo: "admin" },
  { path: "/producto/index", label: "Productos", grupo: "admin" },
  { path: "/producto/importar", label: "Importar productos", grupo: "admin" },
  { path: "/footer/index", label: "Footer", grupo: "admin" },
  { path: "/slider/index", label: "Slider", grupo: "admin" },
  { path: "/about/index", label: "About (redirect)", grupo: "admin" },
  { path: "/planes/index", label: "Planes", grupo: "admin" },
  { path: "/porque_elejirnos/index", label: "Por qué elegirnos", grupo: "admin" },
  { path: "/nuestro_equipo/index", label: "Nuestro equipo", grupo: "admin" },
  { path: "/pedidos/index", label: "Pedidos", grupo: "admin" },
  { path: "/facturas/index", label: "Facturas", grupo: "admin" },
  { path: "/balance_ventas/index", label: "Balance ventas", grupo: "admin" },
  { path: "/categoria/index", label: "Categorías", grupo: "admin" },
  { path: "/promocion/index", label: "Promociones", grupo: "admin" },
  { path: "/ofertas/index", label: "Ofertas del día", grupo: "admin" },
  { path: "/metadatospagina/index", label: "Metadatos página", grupo: "admin" },
  { path: "/envios/index", label: "Envíos", grupo: "admin" },
  { path: "/popular/index", label: "Popular categoría", grupo: "admin" },
  { path: "/libro_reclamo/index", label: "Libro de reclamos", grupo: "admin" },
  { path: "/configuracion/pasarela", label: "Pasarela de pago", grupo: "admin" },
  { path: "/configuracion/auth-proveedor", label: "Auth proveedor", grupo: "admin" },
  { path: "/configuracion/favicon", label: "Favicon", grupo: "admin" },
  { path: "/metodologia/index", label: "Metodología", grupo: "admin" },
  { path: "/servicios/index", label: "Servicios", grupo: "admin" },
  { path: "/faq/index", label: "FAQ", grupo: "admin" },
  { path: "/testimonios/index", label: "Testimonios", grupo: "admin" },
  { path: "/header/index", label: "Header", grupo: "admin" },
  { path: "/carrusel/index", label: "Carrusel", grupo: "admin" },
  { path: "/ejemplares/index", label: "Ejemplares", grupo: "admin" },
  { path: "/portafolio/index", label: "Portafolio", grupo: "admin" },
  { path: "/eventos/index", label: "Eventos", grupo: "admin" },
  { path: "/publicaciones/index", label: "Publicaciones", grupo: "admin" },
  { path: "/contadores/index", label: "Contadores", grupo: "admin" },
  { path: "/pagina-nosotros/index", label: "Página nosotros", grupo: "admin" },
  { path: "/pagina-productos/index", label: "Página productos", grupo: "admin" },
  { path: "/pagina-maquinarias/index", label: "Página maquinarias", grupo: "admin" },
  { path: "/pagina-contacto/index", label: "Página contacto", grupo: "admin" },
  { path: "/producto-destacado/index", label: "Producto destacado", grupo: "admin" },
  { path: "/producto-catalogo/index", label: "Producto catálogo", grupo: "admin" },
  { path: "/linea-producto/index", label: "Línea producto", grupo: "admin" },
  { path: "/videos/index", label: "Videos", grupo: "admin" },
  { path: "/clientes/index", label: "Clientes web", grupo: "admin" },
  { path: "/contacto-landing/index", label: "Contacto landing", grupo: "admin" },
  { path: "/promo-banner/index", label: "Banner promo", grupo: "admin" },
  { path: "/experiencias/index", label: "Experiencias", grupo: "admin" },
  { path: "/masaje-faq/index",          label: "Masaje Tántrico FAQ", grupo: "admin" },
  { path: "/pagina-experiencias/index", label: "Página Experiencias",  grupo: "admin" },
  { path: "/pagina-masajes/index",      label: "Masajes Tántricos",    grupo: "admin" },
  { path: "/pagina-galeria/index", label: "Galería Royal", grupo: "admin" },
  { path: "/contacto-mensajes/index", label: "Mensajes contacto", grupo: "admin" },
  { path: "/about-caracteristica/index", label: "About característica", grupo: "admin" },
  { path: "/confianza-item/index", label: "Confianza item", grupo: "admin" },
  { path: "/informe-sistema/index", label: "Informe sistema", grupo: "admin" },
  { path: "/material/table", label: "Material: Table", grupo: "material" },
  { path: "/material/form", label: "Material: Form", grupo: "material" },
  { path: "/material/buttons", label: "Material: Buttons", grupo: "material" },
  { path: "/material/icons", label: "Material: Icons", grupo: "material" },
  { path: "/material/progress", label: "Material: Progress", grupo: "material" },
  { path: "/material/menu", label: "Material: Menu", grupo: "material" },
  { path: "/material/checkbox", label: "Material: Checkbox", grupo: "material" },
  { path: "/material/switch", label: "Material: Switch", grupo: "material" },
  { path: "/material/radio", label: "Material: Radio", grupo: "material" },
  { path: "/material/slider", label: "Material: Slider", grupo: "material" },
  { path: "/material/autocomplete", label: "Material: Autocomplete", grupo: "material" },
  { path: "/material/expansion-panel", label: "Material: Expansion panel", grupo: "material" },
  { path: "/material/dialog", label: "Material: Dialog", grupo: "material" },
  { path: "/material/snackbar", label: "Material: Snackbar", grupo: "material" },
  { path: "/session/signup", label: "Registro", grupo: "session" },
  { path: "/session/signin", label: "Iniciar sesión", grupo: "session" },
  { path: "/session/oauth-callback", label: "OAuth callback", grupo: "session" },
  { path: "/session/two-factor", label: "2FA", grupo: "session" },
  { path: "/session/two-factor-setup", label: "Configurar 2FA", grupo: "session" },
  { path: "/session/forgot-password", label: "Recuperar contraseña", grupo: "session" },
];

export function normalizePath(url) {
  if (!url || typeof url !== "string") return "";
  const t = url.trim();
  if (!t) return "";
  if (/^https?:\/\//i.test(t) || t.startsWith("#")) return t;
  return t.startsWith("/") ? t : `/${t}`;
}
