const fs = require('fs');
const path = require('path');
const html = fs.readFileSync(path.join(__dirname, '../../../public/temp02/index.html'), 'utf8');
const start = html.indexOf('<section id="hub">');
const end = html.indexOf('<!-- CTA FINAL -->');
if (start < 0 || end < 0) throw new Error('hub not found');
const chunk = html.slice(start, end);
const dest = path.join(__dirname, '../../../resources/views/web/pages/royalsensorymassage/partials/hub_static.blade.php');
fs.mkdirSync(path.dirname(dest), { recursive: true });
fs.writeFileSync(dest, chunk);
console.log('bytes', chunk.length);
